server:
  port: 8900

spring:
  application:
    name: intra_day_loan_balance

  threads:
    virtual:
      enable: true

  mysql:
    datasource:
      url: jdbc:mysql://192.168.150.231:3306/gwbank
#      url: jdbc:mysql://10.10.1.108:3306/gwbank
      username: root
      password: redhat
#      driverClassName: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        pool-name: MYSQL_HIKARI_CP
        max-lifetime: 60000
        connection-timeout: 30000
        leak-detection-threshold: 30000
        connection-test-query: select 1 from dual
    jpa:
      show-sql: false
      open-in-view: false
      hibernate:
        ddl-auto: none
        format-sql: true
        batch-size: 5000

      properties:
        hibernate:
          ddl-auto: none
          dialect: org.hibernate.dialect.MySQL55Dialect
          jdbc:
            batch_size: 500
      database-platform: org.hibernate.dialect.MySQL5Dialect


  oracle:
    datasource:
      url: jdbc:oracle:thin:@10.10.1.199:1521:STAGINGFO
      username: core
      password: trading123
      driverClassName: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        pool-name: ORACLE_BO_HIKARI_CP
        max-lifetime: 60000
        connection-timeout: 30000
        leak-detection-threshold: 30000
        connection-test-query: select 1 from dual
    jpa:
      show-sql: false
      open-in-view: false
      hibernate:
        ddl-auto: none
        format-sql: true
        batch-size: 5000


logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    oracle.jdbc: TRACE

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs.html